BIBER_MEANS = {'VBD': 40.1, 'PEAS': 8.6, 'VPRT': 77.7, 'PLACE': 3.1, 'TIME': 5.2, 'FPP1': 27.2, 'SPP2': 9.9,
               'TPP3': 29.9, 'PIT': 10.3, 'DEMP': 4.6, 'INPR': 1.4, 'PROD': 3.0, 'WHQU': 0.2, 'NOMZ': 19.9, 'GER': 7.0,
               'NN': 180.5, 'PASS': 9.6, 'BYPA': 0.8, 'BEMA': 28.3, 'EX': 2.2, 'THVC': 3.3, 'THAC': 0.3, 'WHCL': 0.6,
               'TO': 14.9, 'PRESP': 1.0, 'PASTP': 0.1, 'WZPAST': 2.5, 'WZPRES': 1.6, 'TSUB': 0.4, 'TOBJ': 0.8,
               'WHSUB': 2.1, 'WHOBJ': 1.4, 'PIRE': 0.7, 'SERE': 0.1, 'CAUS': 1.1, 'CONC': 0.5, 'COND': 2.5, 'OSUB': 1.0,
               'PIN': 110.5, 'JJ': 60.7, 'PRED': 4.7, 'RB': 65.6, 'TTR': 511.0, 'AWL': 45.0, 'CONJ': 1.2, 'DWNT': 2.0,
               'HDG': 0.6, 'AMP': 2.7, 'EMPH': 6.3, 'DPAR': 1.2, 'DEMO': 9.9, 'POMD': 5.8, 'NEMD': 2.1, 'PRMD': 5.6,
               'PUBV': 7.7, 'PRIV': 18.0, 'SUAV': 2.9, 'SMP': 0.8, 'CONT': 13.5, 'THATD': 3.1, 'STPR': 2.0, 'SPIN': 0,
               'SPAU': 5.5, 'PHC': 3.4, 'ANDC': 4.5, 'SYNE': 1.7, 'XX0': 8.5}

BIBER_SDS = {'VBD': 30.4, 'PEAS': 5.2, 'VPRT': 34.3, 'PLACE': 3.4, 'TIME': 3.5, 'FPP1': 26.1, 'SPP2': 13.8,
             'TPP3': 22.5, 'PIT': 7.1, 'DEMP': 4.8, 'INPR': 2.0, 'PROD': 3.5, 'WHQU': 0.6, 'NOMZ': 14.4, 'GER': 3.8,
             'NN': 35.6, 'PASS': 6.6, 'BYPA': 1.3, 'BEMA': 9.5, 'EX': 1.8, 'THVC': 2.9, 'THAC': 0.6, 'WHCL': 1.0,
             'TO': 5.6, 'PRESP': 1.7, 'PASTP': 0.4, 'WZPAST': 3.1, 'WZPRES': 1.8, 'TSUB': 0.8, 'TOBJ': 1.1,
             'WHSUB': 2.0, 'WHOBJ': 1.7, 'PIRE': 1.1, 'SERE': 0.4, 'CAUS': 1.7, 'CONC': 0.8, 'COND': 2.2, 'OSUB': 1.1,
             'PIN': 25.4, 'JJ': 18.8, 'PRED': 2.6, 'RB': 17.6, 'TTR': 52.0, 'AWL': 4.0, 'CONJ': 1.6, 'DWNT': 1.6,
             'HDG': 1.3, 'AMP': 2.6, 'EMPH': 4.2, 'DPAR': 2.3, 'DEMO': 4.2, 'POMD': 3.5, 'NEMD': 2.1, 'PRMD': 4.2,
             'PUBV': 5.4, 'PRIV': 10.4, 'SUAV': 3.1, 'SMP': 1.0, 'CONT': 18.6, 'THATD': 4.1, 'STPR': 2.7, 'SPIN': 0.0,
             'SPAU': 2.5, 'PHC': 2.7, 'ANDC': 4.8, 'SYNE': 1.6, 'XX0': 6.1}

TAGS_BY_DIMENSION = {
    '1_pos': ['PRIV', 'THATD', 'CONT', 'VPRT', 'SPP2', 'PROD', 'XX0', 'DEMP', 'EMPH', 'FPP1', 'PIT', 'BEMA', 'CAUS',
              'DPAR', 'INPR', 'AMP', 'POMD', 'ANDC', 'STPR'],
    '1_neg': ['NN', 'AWL', 'PIN', 'TTR', 'JJ'],
    '2_pos': ['VBD', 'TPP3', 'PEAS', 'PUBV', 'SYNE', 'PRESP'],
    '2_neg': [],
    '3_pos': ['WHOBJ', 'WHSUB', 'PHC', 'NOMZ'],
    '3_neg': ['TIME', 'PLACE', 'RB'],
    '4_pos': ['TO', 'PRMD', 'SUAV', 'COND', 'NEMD', 'SPAU'],
    '4_neg': [],
    '5_pos': ['CONJ', 'PASS', 'WZPAST', 'OSUB'],
    '5_neg': [],
    '6_pos': ['THVC', 'DEMO'],
    '6_neg': []
}

ALL_TAGS = [
    'QUAN',
    'QUPR',
    'AMP',
    'PASS',
    'XX0',
    'JJ',
    'BEMA',
    'CAUS',
    'CONC',
    'COND',
    'CONJ',
    'CONT',
    'DPAR',
    'DWNT',
    'EX',
    'FPP1',
    'GER',
    'RB',
    'PIN',
    'INPR',
    'TO',
    'NEMD',
    'OSUB',
    'PASTP',
    'VBD',
    'PHC',
    'PIRE',
    'PLACE',
    'POMD',
    'PRMD',
    'WZPRES',
    'VPRT',
    'PRIV',
    'PIT',
    'PUBV',
    'SPP2',
    'SMP',
    'SERE',
    'STPR',
    'SUAV',
    'SYNE',
    'TPP3',
    'TIME',
    'NOMZ',
    'BYPA',
    'PRED',
    'TOBJ',
    'TSUB',
    'THVC',
    'NN',
    'DEMP',
    'DEMO',
    'WHQU',
    'EMPH',
    'HDG',
    'WZPAST',
    'THAC',
    'PEAS',
    'ANDC',
    'PRESP',
    'PROD',
    'SPAU',
    'SPIN',
    'THATD',
    'WHOBJ',
    'WHSUB',
    'WHCL'
]

DOC_TAGS = [
    'AWL',
    'TTR',
    'RB'
]

# Keep track of all the acronyms in one spot
MDA_ACRONYMS = {
    'XXO': 'Analytic Negation',
    'SYNE': 'Synthetic Negation'
}
